version: "3.7"
services:
  terraform:
    image: hashicorp/terraform:1.6.6
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      # These env-vars are set up temporarily by aws-vault
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
